spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://159.75.211.245:3306/course?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: pwh_course
server:
  port: 9001
  servlet:
    context-path: /system
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coderpwh.system.domain
