spring:
  application:
    name: business
server:
  port: 9002
  servlet:
    context-path: /business

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
